### ISSUE TITLE
Problems on 3.12-3.16

### ISSUE THREAD

**Issue by l300lvl** [simonthechipmunk/jumptooverview#1]
Hello there,

Been following your updates for some time now, but since I'd been trying to update Overview On Startup myself since 3.12, I've had problems. Notably, it seems to randomly not work under certain conditions. For instance, when there are minimized windows under at LEAST 3.14 and 3.16, this error occurs(with my work and yours):

> pushModal: invocation of begin_modal failed

the error is logged, and the overview never appears. upon going into the overview, if applications/frequent view was enabled, they open properly as if they got the signal. this is visible from terminal after having all windows minimized and running gnome-shell --replace from terminal, then minimizing windows, then running alt+f2 and r

it is also occuring with my older work under 3.12, 3.14, and 3.16, even with some of your changes but not others. the timeout seems not to matter, but i have an open issue myself regarding this same problem. https://github.com/l300lvl/overview-on-startup-extension/issues/1

if youll notice the bug that was actually logged and reported back regards 3.14, but they never opened a new bug for the specific case. perhaps something to do with how windows handle focus since after a shell restart no windows usually have focus? when i use this on 3.10 it works as normal.

regards, and hopefully we can work this out somehow, it may be a bug... let me know if i can help in any way, my email is back working and im active again.

**Comment by l300lvl** [comment]
other info hopefully, this is the full log:

> Gjs-Message: JS WARNING: [/home/l300lvl/.local/share/gnome-shell/extensions/jumptooverview@simonthechipmunk.noreply.com/utils.js 67]: variable domain redeclares argument
> Gjs-Message: JS WARNING: [/home/l300lvl/.local/share/gnome-shell/extensions/jumptooverview@simonthechipmunk.noreply.com/extension.js 166]: assignment to undeclared variable i
> Gjs-Message: JS LOG: pushModal: invocation of begin_modal failed

**Comment by simonthechipmunk** [comment]
Hi,
thanks for the information on this issue. First of all I actually never tried to run "gnome-shell --replace". Shame on me since it shows a great deal of useful data. Fixing the GS-WARNINGs is quite easy and I will have to do this for all my extensions (they all use the same version of utils.js). Also the line
`let domain = domain || Me.metadata['gettext-domain'];`
i found in someone's extension left me suspicious from the beginning. Turns out I had the right feeling about that :)

Maybe I should mention that I only started programming about 6 months ago so I'm a bloody beginner going through 'learning by doing'.

Now for the real problem
I was able to reproduce the bug you describe here but I have no idea where this is coming from:
`Gjs-Message: JS LOG: pushModal: invocation of begin_modal failed`
A short google search for the message didn't bring up anything useful so far.

In my version showing the overview should be prevented when there is any open window on any active workspace at shell restart, because in that case the overview wouldn't load correctly and show window glitches (see https://drive.google.com/folderview?id=0BznE_vFGfQoNfnVWUnViY01WWkVJM1VvbjNTcTNUSzJqWE1TRkdzTGFRQkJTMHNtSjE3SGs&usp=sharing )
However this only seems true for GS versions prior to 3.16 as I tested it and the glitches are gone _yay_.

The code that is most likely causing the problems is the startup check loop for open windows which is calling the overview function (which it shouldn't do in the first place) but only executes the part where the viewselector is activated (for whatever stupid reason. It's the same function after all!) This then results in the overview not showing, but jumping to the 'frequent' view with the next call for the overview.
If I comment out the check loop (l165 - l183), the overview starts just fine.
https://github.com/simonthechipmunk/jumptooverview/blob/master/extension.js#L165

I will check this as soon as possible and report back if I find something. I hope we can get this worked out.

**Comment by simonthechipmunk** [comment]
Ok right now I'm digging into this:

The problem seems to be that we are trying to list windows in a very early state of gnome-shell starting up. respectively: 

```
let windows = global.screen.get_workspace_by_index(i).list_windows();
```

While this is working fine for Shell 3.10, from 3.12 onwards this function call just returns an empty array despite there being open windows on the requested work space. This results in the extension going havoc and the corresponding error message which is returned whenever grabbing mouse/keyboard focus to a window was unsuccessful. (Which seems logical because we are trying to grab windows that are there but aren't known to the windowmanager yet)

```
Gjs-Message: JS LOG: pushModal: invocation of begin_modal failed
```

This leads to the big question: Why?
If I'd have to take a guess, I would assume that since GS3.12 the extension system gets initialized before the window manager. Running my function call just 200ms later, results in everything working fine but that isn't a fix but a stupid workaround.

Interestingly in latest shell versions I can just run

```
let actors = global.get_window_actors();
```

which returns an empty array as long as the windowmanager isn't running properly and returns 1 array entry when it is up and good even if there is no open window on any desktop.
I could test for this easily but this is just testing for another bug to fix my bug. Great bugception there.
The windowmanager shouldn't return a window instance when there is no window open.

HALP!

**Comment by simonthechipmunk** [comment]
Got it. So the window manager showing one window instance despite no windows being open is actually a desired behaviour (according to the helpful people on gnome IRC). It is actually the Shell itself (wm_class:Gnome-Shell).
For the actual fix though taking a look at the layoutmanager.js helped me. The Startup animation of Gnome-Shell (which is horrible anyway. just my two bits) is actually held back until the mainloop turns idle. If I apply the same mainloop event to my workspace check I can make sure the Shell is fully loaded before running any actions on the windowmanager, resulting in a perfectly working extension again:

```
// Check for startup conditions as soon as the mainloop turns idle

    eventStartup = GLib.idle_add(GLib.PRIORITY_LOW, function() { 
        _checkStartup();
        return false;

    });
```

**Comment by l300lvl** [comment]
WOW. This one really did take some time, but you are awesome for finally figuring it out. I have been working tons and trying to take that more serious and learn more to do with the field I'm working in, but I did not forget this issue. Anyways...

That is amazing news. I think I can use this in Show-Desktop-Button as well. I am going to look over the pull request you made, I'm sure it's right but I want to check it obviously, and I need to get 3.18 going as well. So this gives me some inspiration I've been waiting for. This will make tons of people happy, and perhaps now a bug can actually be opened against Mutter/clutter or whatever is causing this.

Much respect, again. I have to update several extensions like I said in the other comment, and I plan to remove the version code I have been using finally. But first I will accept your pull request and check it out, I'm freaking excited!
